#!/bin/bash

set -euo pipefail

TEAM_INPUT="${1:?team is required}"
ROLE_NAME="${2:?role is required}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$SCRIPT_DIR"
# shellcheck disable=SC1091
source "$SCRIPTS_DIR/load-team-manifest.sh"

load_team_manifest "$TEAM_INPUT"
init_team_runtime_state
load_role_manifest "$ROLE_NAME"

STATE_FILE="$TEAM_RUNTIME_SUBAGENTS_DIR/$ROLE_NAME.env"

# shellcheck disable=SC1090
source "$STATE_FILE"

MODE="${NEW_MODE:-${MODE:-manifest-default}}"
OWNER="${NEW_OWNER:-${OWNER:-$ROLE_WORKDIR_REL}}"
AGENT_ID="${NEW_AGENT_ID:-${AGENT_ID:-"-"}}"
MODEL="${NEW_MODEL:-${MODEL:-${ROLE_DEFAULT_MODEL:-$TEAM_DEFAULT_MODEL}}}"
STATUS="${NEW_STATUS:-${STATUS:-${ROLE_DEFAULT_STATUS:-not-started}}}"
BRANCH="${NEW_BRANCH:-${BRANCH:-${ROLE_DEFAULT_BRANCH:-"-"}}}"
LAST_UPDATED="${NEW_LAST_UPDATED:-$(date '+%Y-%m-%dT%H:%M:%S%z')}"
CURRENT_TASK="${NEW_CURRENT_TASK:-${CURRENT_TASK:-${ROLE_DEFAULT_TASK:-"-"}}}"
LAST_MESSAGE="${NEW_LAST_MESSAGE:-${LAST_MESSAGE:-${ROLE_DEFAULT_MESSAGE:-"-"}}}"

cat >"$STATE_FILE" <<EOF
ROLE=$ROLE_NAME
MODE="$MODE"
OWNER="$OWNER"
AGENT_ID="$AGENT_ID"
MODEL="$MODEL"
STATUS="$STATUS"
BRANCH="$BRANCH"
LAST_UPDATED="$LAST_UPDATED"
CURRENT_TASK="$CURRENT_TASK"
LAST_MESSAGE="$LAST_MESSAGE"
EOF
