name: Create GitHub Labels

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/labels.yml"

permissions:
  contents: read
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync labels from YAML
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ github.token }}
